name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.fairuzz }}
        password: ${{ secrets.dckr_pat_ivToj1rJNspbKQrKKOSfBYy-qZA }}

    - name: Build the Docker image
      run: docker build . -t fairuzz/flask-ml-docker

    - name: Push the Docker image
      run: docker push fairuzz/flask-ml-docker
